version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/code
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: learngual
      POSTGRES_USER: learngual
      POSTGRES_PASSWORD: learngual

    ports:
      - 5433:5432

    volumes:
      - learngual:/var/lib/postgresql/data

  redis-db:
   image: redis
   restart: always



volumes:
  learngual:
