# Generated by Django 5.0.3 on 2024-03-14 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwt',
            name='refresh_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 12, 28, 16, 156252, tzinfo=datetime.timezone.utc)),
        ),
    ]
