# Generated by Django 5.0.3 on 2024-03-15 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_jwt_refresh_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwt',
            name='refresh_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 14, 29, 38, 316621, tzinfo=datetime.timezone.utc)),
        ),
    ]
