# Generated by Django 5.0.3 on 2025-09-11 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_jwt_refresh_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwt',
            name='refresh_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 20, 42, 0, 354765, tzinfo=datetime.timezone.utc)),
        ),
    ]
