# Generated by Django 5.0.3 on 2025-09-12 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_jwt_refresh_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwt',
            name='refresh_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
