# Generated by Django 5.0.3 on 2024-03-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='voice_note',
        ),
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='chat', to='chatapp.messagemodel'),
        ),
    ]
