# Generated by Django 5.0.3 on 2025-09-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_form_submission_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_submission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Form_Submission',
        ),
    ]
